
stations = ["Akademmistechko", "Zhytomyrska", "Sviatoshyn", "Nyvky", "Beresteiska",
            "Shuliavska", "Politekhnichnyi Instytut", "Vokzalna", "Universytet",
            "Teatralna", "Khreschatyk", "Arsenalna", "Dnipro", "Hidropark", "Livoberezhna", "Darnytsia", "Chernihivska",
            "Lisova",
            "Heroiv Dnipra", "Minska", "Obolon", "Pochaina", "Tarasa Shevchenka",
            "Kontraktova", "Poshtova", "Maidan Nezalezhnosti",
            "Ploshcha Lva Tolstoho", "Olimpiiska", "Palats 'Ukrayina'", "Lybidska",
            "Demiivska", "Holosiivska", "Vasylkivska", "Vystavkovyi Tsentr", "Ipodrom",
            "Teremky",
            "Syrets", "Dorohozhychi", "Lukianivska", "Zoloti vorota", "Palats sportu", "Klovska", "Pecherska",
            "Druzhby narodiv", "Vydubychi", "Slavutych", "Osokorky", "Pozniaky", "Kharkivska",
            "Vyrlytsia", "Boryspilska", "Chervonyi Khutir"]


red_line = [("Akademmistechko", "Zhytomyrska", {'weight': 1}),
            ("Zhytomyrska", "Sviatoshyn", {'weight': 2}),
            ("Sviatoshyn", "Nyvky", {'weight': 3}),
            ("Nyvky", "Beresteiska", {'weight': 1}),
            ("Beresteiska", "Shuliavska", {'weight': 2}),
            ("Shuliavska", "Politekhnichnyi Instytut", {'weight': 1}),
            ("Politekhnichnyi Instytut", "Vokzalna", {'weight': 3}),
            ("Vokzalna", "Universytet", {'weight': 2}),
            ("Universytet", "Teatralna", {'weight': 1}),
            ("Teatralna", "Khreschatyk", {'weight': 2}),
            ("Khreschatyk", "Arsenalna", {'weight': 3}),
            ("Arsenalna", "Dnipro", {'weight': 1}),
            ("Dnipro", "Hidropark", {'weight': 2}),
            ("Hidropark", "Livoberezhna", {'weight': 3}),
            ("Livoberezhna", "Darnytsia", {'weight': 1}),
            ("Darnytsia", "Chernihivska", {'weight': 2}),
            ("Chernihivska", "Lisova", {'weight': 3})]

blue_line = [("Heroiv Dnipra", "Minska", {'weight': 1}),
             ("Minska", "Obolon", {'weight': 2}),
             ("Obolon", "Pochaina", {'weight': 3}),
             ("Pochaina", "Tarasa Shevchenka", {'weight': 1}),
             ("Tarasa Shevchenka", "Kontraktova", {'weight': 2}),
             ("Kontraktova", "Poshtova", {'weight': 3}),
             ("Poshtova", "Maidan Nezalezhnosti", {'weight': 1}),
             ("Maidan Nezalezhnosti", "Ploshcha Lva Tolstoho", {'weight': 2}),
             ("Ploshcha Lva Tolstoho", "Olimpiiska", {'weight': 3}),
             ("Olimpiiska", "Palats 'Ukrayina'", {'weight': 1}),
             ("Palats 'Ukrayina'", "Lybidska", {'weight': 2}),
             ("Lybidska", "Demiivska", {'weight': 3}),
             ("Demiivska", "Holosiivska", {'weight': 1}),
             ("Holosiivska", "Vasylkivska", {'weight': 2}),
             ("Vasylkivska", "Vystavkovyi Tsentr", {'weight': 3}),
             ("Vystavkovyi Tsentr", "Ipodrom", {'weight': 1}),
             ("Ipodrom", "Teremky", {'weight': 2})]

green_line = [("Syrets", "Dorohozhychi", {'weight': 1}),
              ("Dorohozhychi", "Lukianivska", {'weight': 2}),
              ("Lukianivska", "Zoloti vorota", {'weight': 3}),
              ("Zoloti vorota", "Palats sportu", {'weight': 1}),
              ("Palats sportu", "Klovska", {'weight': 2}),
              ("Klovska", "Pecherska", {'weight': 3}),
              ("Pecherska", "Druzhby narodiv", {'weight': 1}),
              ("Druzhby narodiv", "Vydubychi", {'weight': 2}),
              ("Vydubychi", "Slavutych", {'weight': 3}),
              ("Slavutych", "Osokorky", {'weight': 1}),
              ("Osokorky", "Pozniaky", {'weight': 2}),
              ("Pozniaky", "Kharkivska", {'weight': 3}),
              ("Kharkivska", "Vyrlytsia", {'weight': 1}),
              ("Vyrlytsia", "Boryspilska", {'weight': 2}),
              ("Boryspilska", "Chervonyi Khutir", {'weight': 3})]

transfers = [("Maidan Nezalezhnosti", "Khreschatyk", {'weight': 1}),
             ("Zoloti vorota", "Teatralna", {'weight': 1}),
             ("Ploshcha Lva Tolstoho", "Palats sportu", {'weight': 1})]


posion_station = {
    "Akademmistechko": (-15, 10), 
    "Zhytomyrska": (-15, 7.5),
    "Sviatoshyn": (-14, 5), 
    "Nyvky": (-14, 2.5),
    "Beresteiska": (-13, 1), 
    "Shuliavska": (-11, -1),
    "Politekhnichnyi Instytut": (-9, -1),
    "Vokzalna": (-7, -2),
    "Universytet": (-5, -2),
    "Teatralna": (-3, -2),
    "Khreschatyk": (2, 1),
    "Arsenalna": (4, -1),
    "Dnipro": (7, -1),
    "Hidropark": (10, -1),
    "Livoberezhna": (13, 2), 
    "Darnytsia": (16, 3),
    "Chernihivska": (19, 5), 
    "Lisova": (22, 7),
    "Heroiv Dnipra": (0, 17),
    "Minska": (0, 15),
    "Obolon": (0, 13), 
    "Pochaina": (0, 10),
    "Tarasa Shevchenka": (0, 8), 
    "Kontraktova": (0, 6),
    "Poshtova": (0, 4),
    "Maidan Nezalezhnosti": (0, 2),
    "Ploshcha Lva Tolstoho": (-0.5, -5),
    "Olimpiiska": (-1, -7),
    "Palats 'Ukrayina'": (-2, -9), 
    "Lybidska": (-2, -11),
    "Demiivska": (-3, -12), 
    "Holosiivska": (-6, -13),
    "Vasylkivska": (-8, -15),
    "Vystavkovyi Tsentr": (-12, -15),
    "Ipodrom": (-15, -15),
    "Teremky": (-18, -15),
    "Syrets": (-8, 13), 
    "Dorohozhychi": (-7, 10),
    "Lukianivska": (-6, 6),
    "Zoloti vorota": (-2, 2),
    "Palats sportu": (1, -2), 
    "Klovska": (3, -4),
    "Pecherska": (5, -6), 
    "Druzhby narodiv": (7, -9),
    "Vydubychi": (9, -11),
    "Slavutych": (11, -15),
    "Osokorky": (13, -16),
    "Pozniaky": (14, -17),
    "Kharkivska": (16, -19), 
    "Vyrlytsia": (18, -22),
    "Boryspilska": (20, -24),
    "Chervonyi Khutir": (22, -26),
}